module.exports = {
  plugins: ["stylelint-scss", "stylelint-order"],
  rules: {
    indentation: "tab",
    "max-empty-lines": [
      0,
      {
        ignore: "comments",
      },
    ],
    "no-eol-whitespace": true,
    "no-missing-end-of-source-newline": true,
    "no-empty-first-line": true,
    "at-rule-no-unknown": true,
    "at-rule-name-case": "lower",
    "at-rule-name-space-after": "always",
    "at-rule-semicolon-newline-after": "always",
    "at-rule-semicolon-space-before": "never",
    "block-closing-brace-empty-line-before": "never",
    "block-opening-brace-newline-after": "always",
    "block-no-empty": true,
    "color-hex-case": "lower",
    "color-named": "never",
    "comment-no-empty": true,
    "comment-whitespace-inside": "always",
    "comment-empty-line-before": "never",
    "custom-property-empty-line-before": "never",
    "declaration-bang-space-after": "never",
    "declaration-bang-space-before": "always",
    "declaration-block-no-duplicate-properties": true,
    "declaration-block-no-shorthand-property-overrides": true,
    "declaration-block-no-redundant-longhand-properties": true,
    "declaration-colon-space-after": "always",
    "declaration-colon-space-before": "never",
    "declaration-block-trailing-semicolon": "always",
    "function-comma-space-after": "always",
    "function-comma-space-before": "never",
    "function-max-empty-lines": 0,
    "media-feature-colon-space-after": "always",
    "media-feature-colon-space-before": "never",
    "media-feature-name-case": "lower",
    "media-feature-parentheses-space-inside": "never",
    "media-feature-range-operator-space-after": "always",
    "media-feature-range-operator-space-before": "always",
    "media-query-list-comma-newline-after": "always-multi-line",
    "media-query-list-comma-newline-before": "never-multi-line",
    "no-extra-semicolons": true,
    "number-leading-zero": "always",
    "number-no-trailing-zeros": true,
    "property-case": "lower",
    "property-no-unknown": [
      true,
      {
        severity: "error",
      },
    ],
    "rule-empty-line-before": "never",
    "selector-pseudo-class-no-unknown": true,
    "selector-pseudo-element-no-unknown": true,
    "selector-type-no-unknown": true,
    "shorthand-property-no-redundant-values": true,
    "unit-case": "lower",
    "value-keyword-case": "lower",
    "value-list-comma-newline-after": "always-multi-line",
    "value-list-comma-space-after": "always-single-line",
    "value-list-comma-space-before": "never",
    "order/order": [["custom-properties", "at-variables", "declarations", "rules", "at-rules"]],
    "order/properties-order": [
      [
        "content",
        "float",
        "position",
        "top",
        "right",
        "bottom",
        "left",
        "display",
        "vertical-align",
        "z-index",
        "width",
        "height",
        "margin",
        "margin-top",
        "margin-right",
        "margin-bottom",
        "margin-left",
        "padding",
        "padding-top",
        "padding-right",
        "padding-bottom",
        "padding-left",
        "border",
        "border-style",
        "border-width",
        "border-color",
        "border-radius",
        "background",
        "background-image",
        "background-repeat",
        "background-position",
        "background-size",
        "box-shadow",
        "font-size",
        "font-weight",
        "line-height",
        "color",
        "text-decoration",
        "word-break",
        "white-space",
        "text-overflow",
        "animation",
        "animation-duration",
        "animation-timing-function",
        "animation-delay",
        "animation-iteration-count",
        "animation-fill-mode",
        "animation-direction",
        "animation-play-state",
        "animation-name",
        "transform",
        "overflow",
        "clear",
      ],
    ],
  },
  defaultSeverity: "warning",
};
